# Generated by Django 6.0.2 on 2026-02-23 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0003_alter_user_password_hash_emailotp"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        choices=[
                            ("nav_click", "Nav Click"),
                            ("power_source_card_click", "Power Source Card Click"),
                            ("industry_card_click", "Industry Card Click"),
                            ("product_filters_applied", "Product Filters Applied"),
                            ("product_click", "Product Click"),
                            ("product_detail_view", "Product Detail View"),
                            ("product_detail_tab_click", "Product Detail Tab Click"),
                            ("request_quote_click", "Request Quote Click"),
                            ("document_download_click", "Document Download Click"),
                            ("document_email_request_open", "Document Email Request Open"),
                            ("document_email_request_submit", "Document Email Request Submit"),
                            ("document_email_request_submit_failed", "Document Email Request Submit Failed"),
                            ("page_engagement", "Page Engagement"),
                        ],
                        max_length=64,
                    ),
                ),
                ("event_time", models.DateTimeField()),
                ("session_id", models.CharField(max_length=128)),
                ("anon_id", models.CharField(max_length=128)),
                ("page_path", models.CharField(max_length=500)),
                ("page_title", models.CharField(blank=True, default="", max_length=255)),
                ("referrer", models.CharField(blank=True, default="", max_length=500)),
                ("properties", models.JSONField(blank=True, default=dict)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("device_type", models.CharField(blank=True, default="", max_length=32)),
                ("request_location", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_events",
                "indexes": [
                    models.Index(fields=["event_name"], name="analytics_e_event_n_850fd0_idx"),
                    models.Index(fields=["event_time"], name="analytics_e_event_t_b93e62_idx"),
                    models.Index(fields=["user"], name="analytics_e_user_id_f525be_idx"),
                    models.Index(fields=["session_id"], name="analytics_e_session_b3cbf5_idx"),
                    models.Index(fields=["anon_id"], name="analytics_e_anon_id_b787ea_idx"),
                    models.Index(fields=["event_name", "event_time"], name="analytics_e_event_n_2cd1b4_idx"),
                    models.Index(fields=["user", "event_time"], name="analytics_e_user_id_8b61b0_idx"),
                ],
            },
        ),
    ]
