# Generated by Django 6.0.2 on 2026-02-07 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_login_ip",
        ),
    ]
