# Generated by Django 6.0.2 on 2026-02-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_user_last_login_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password_hash",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.CreateModel(
            name="EmailOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "purpose",
                    models.CharField(
                        choices=[("SIGNUP", "Signup"), ("LOGIN", "Login")],
                        max_length=16,
                    ),
                ),
                ("otp_hash", models.CharField(max_length=128)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "email_otps",
                "indexes": [
                    models.Index(
                        fields=["email", "purpose", "is_used", "expires_at"],
                        name="email_otps_email_13d581_idx",
                    )
                ],
            },
        ),
    ]
