# Generated by Django 6.0.2 on 2026-02-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="image_url",
            field=models.ImageField(blank=True, max_length=500, upload_to="achievements/"),
        ),
        migrations.AlterField(
            model_name="news",
            name="cover_image_url",
            field=models.ImageField(blank=True, max_length=500, upload_to="news/"),
        ),
    ]
