# Generated by Django 6.0.2 on 2026-02-07 07:15

import content.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_alter_news_and_achievement_image_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="image_url",
            field=models.ImageField(
                blank=True,
                max_length=500,
                upload_to="achievements/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "webp"]
                    ),
                    content.models.validate_image_file_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="summary",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    django.core.validators.MaxLengthValidator(500),
                    django.core.validators.RegexValidator(
                        ".*\\S.*", "Summary cannot be blank."
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="announcementribbon",
            name="text",
            field=models.TextField(
                max_length=60,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    django.core.validators.MaxLengthValidator(60),
                    django.core.validators.RegexValidator(
                        ".*\\S.*", "Text cannot be blank."
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="cover_image_url",
            field=models.ImageField(
                blank=True,
                max_length=500,
                upload_to="news/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "webp"]
                    ),
                    content.models.validate_image_file_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="summary",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    django.core.validators.MaxLengthValidator(500),
                    django.core.validators.RegexValidator(
                        ".*\\S.*", "Summary cannot be blank."
                    ),
                ]
            ),
        ),
    ]
