# Generated by Django 6.0.2 on 2026-02-11 10:35

import content.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_alter_achievement_image_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AchievementImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        max_length=500,
                        upload_to="achievements/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "webp"]
                            ),
                            content.models.validate_image_file_size,
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="content.achievement",
                    ),
                ),
            ],
            options={
                "db_table": "achievement_images",
            },
        ),
        migrations.CreateModel(
            name="NewsImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        max_length=500,
                        upload_to="news/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "webp"]
                            ),
                            content.models.validate_image_file_size,
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="content.news",
                    ),
                ),
            ],
            options={
                "db_table": "news_images",
            },
        ),
    ]
