# Generated by Django 6.0.2 on 2026-02-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_achievementimage_newsimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievementimage",
            name="display_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="newsimage",
            name="display_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelOptions(
            name="achievementimage",
            options={"ordering": ("display_order", "id")},
        ),
        migrations.AlterModelOptions(
            name="newsimage",
            options={"ordering": ("display_order", "id")},
        ),
    ]