# Generated by Django 6.0.2 on 2026-02-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_add_image_display_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="slug",
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="news",
            name="slug",
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
    ]
