# Generated by Django 6.0.2 on 2026-02-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_achievement_slug_news_slug"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="achievement",
            index=models.Index(fields=["created_at"], name="achievement_created_idx"),
        ),
        migrations.AddIndex(
            model_name="achievement",
            index=models.Index(fields=["is_visible", "-created_at"], name="ach_visible_created_idx"),
        ),
        migrations.AddIndex(
            model_name="news",
            index=models.Index(fields=["created_at"], name="news_created_idx"),
        ),
        migrations.AddIndex(
            model_name="news",
            index=models.Index(fields=["is_visible", "-created_at"], name="news_visible_created_idx"),
        ),
    ]
