# Generated by Django 6.0.2 on 2026-02-06 11:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            django.core.validators.RegexValidator(
                                ".*\\S.*", "Name cannot be blank."
                            ),
                        ],
                    ),
                ),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "short_description",
                    models.TextField(
                        blank=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                ".*\\S.*", "Short description cannot be blank."
                            )
                        ],
                    ),
                ),
                ("is_visible", models.BooleanField(default=True)),
                ("features", models.JSONField(blank=True, null=True)),
                ("operating_conditions", models.JSONField(blank=True, null=True)),
                (
                    "output_torque",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                ("temperature_range", models.JSONField(blank=True, null=True)),
                (
                    "max_allowable_operating_pressure",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                ("mounting_certifications", models.JSONField(blank=True, null=True)),
                ("options", models.JSONField(blank=True, null=True)),
                ("applications", models.JSONField(blank=True, null=True)),
                ("control_options", models.JSONField(blank=True, null=True)),
                (
                    "power_source",
                    models.TextField(
                        blank=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                ".*\\S.*", "Power source cannot be blank."
                            )
                        ],
                    ),
                ),
                ("enclosure_ratings", models.JSONField(blank=True, null=True)),
                ("supply_media", models.JSONField(blank=True, null=True)),
                ("testing_standards", models.JSONField(blank=True, null=True)),
                ("valve_compatibility", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "products",
            },
        ),
        migrations.CreateModel(
            name="ProductCatalogue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200,
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            django.core.validators.RegexValidator(
                                ".*\\S.*", "Title cannot be blank."
                            ),
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                ".*\\S.*", "Description cannot be blank."
                            )
                        ],
                    ),
                ),
                ("file_url", models.URLField(max_length=500)),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("DIRECT", "Direct"),
                            ("EMAIL_VALIDATED", "Email Validated"),
                        ],
                        default="DIRECT",
                        max_length=32,
                    ),
                ),
                ("is_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalogues",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_catalogues",
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            django.core.validators.RegexValidator(
                                ".*\\S.*", "Name cannot be blank."
                            ),
                        ],
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="products.productcategory",
                    ),
                ),
            ],
            options={
                "db_table": "product_categories",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="products.productcategory",
            ),
        ),
    ]
