# Generated by Django 6.0.2 on 2026-02-14 09:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            django.core.validators.RegexValidator(
                                ".*\\S.*", "Name cannot be blank."
                            ),
                        ],
                    ),
                ),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "industries",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PowerSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            django.core.validators.RegexValidator(
                                ".*\\S.*", "Name cannot be blank."
                            ),
                        ],
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        blank=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                ".*\\S.*", "Short description cannot be blank."
                            )
                        ],
                    ),
                ),
                ("image_url", models.TextField(blank=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "power_sources",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AlterModelOptions(
            name="productcatalogue",
            options={"ordering": ["sort_order", "title"]},
        ),
        migrations.AlterModelOptions(
            name="productcategory",
            options={"ordering": ["sort_order", "name"]},
        ),
        migrations.RemoveField(
            model_name="product",
            name="control_options",
        ),
        migrations.RemoveField(
            model_name="product",
            name="enclosure_ratings",
        ),
        migrations.RemoveField(
            model_name="product",
            name="max_allowable_operating_pressure",
        ),
        migrations.RemoveField(
            model_name="product",
            name="mounting_certifications",
        ),
        migrations.RemoveField(
            model_name="product",
            name="operating_conditions",
        ),
        migrations.RemoveField(
            model_name="product",
            name="options",
        ),
        migrations.RemoveField(
            model_name="product",
            name="output_torque",
        ),
        migrations.RemoveField(
            model_name="product",
            name="short_description",
        ),
        migrations.RemoveField(
            model_name="product",
            name="supply_media",
        ),
        migrations.RemoveField(
            model_name="product",
            name="temperature_range",
        ),
        migrations.RemoveField(
            model_name="product",
            name="testing_standards",
        ),
        migrations.AddField(
            model_name="product",
            name="accessories_mounting",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="actuation_type",
            field=models.TextField(
                blank=True,
                validators=[
                    django.core.validators.RegexValidator(
                        ".*\\S.*", "Actuation type cannot be blank."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="certifications",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="control_type",
            field=models.TextField(
                blank=True,
                validators=[
                    django.core.validators.RegexValidator(
                        ".*\\S.*", "Control type cannot be blank."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True,
                validators=[
                    django.core.validators.RegexValidator(
                        ".*\\S.*", "Description cannot be blank."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="double_acting_torque",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="enclosure_rating",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="mounting_standard",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="operating_pressure_max",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="output_torque_max",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="output_torque_min",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.TextField(
                blank=True,
                validators=[
                    django.core.validators.RegexValidator(
                        ".*\\S.*", "Product type cannot be blank."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="short_summary",
            field=models.TextField(
                blank=True,
                validators=[
                    django.core.validators.RegexValidator(
                        ".*\\S.*", "Short summary cannot be blank."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="spring_return_torque",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="temperature_high_max",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="temperature_low_min",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="temperature_standard_max",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="temperature_standard_min",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="testing_standard",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="thrust_max",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="thrust_min",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="productcatalogue",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("CATALOGUE", "Catalogue"),
                    ("DATASHEET", "Datasheet"),
                    ("MANUAL", "Manual"),
                    ("CERTIFICATE", "Certificate"),
                    ("DRAWING", "Drawing"),
                    ("OTHER", "Other"),
                ],
                default="CATALOGUE",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="productcatalogue",
            name="sort_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="products.productcategory",
            ),
        ),
        migrations.AlterModelTable(
            name="productcatalogue",
            table="product_documents",
        ),
        migrations.AlterField(
            model_name="product",
            name="power_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="products.powersource",
            ),
        ),
        migrations.CreateModel(
            name="ProductIndustry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "industry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.industry",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_industries",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="industries",
            field=models.ManyToManyField(
                related_name="products",
                through="products.ProductIndustry",
                to="products.industry",
            ),
        ),
        migrations.AddConstraint(
            model_name="productindustry",
            constraint=models.UniqueConstraint(
                fields=("product", "industry"), name="uniq_product_industry"
            ),
        ),
    ]
