# Generated by Django 6.0.2 on 2026-02-14 09:27

import django.core.validators
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0003_industry_powersource_alter_productcatalogue_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="powersource",
            name="image_url",
            field=models.ImageField(
                blank=True,
                max_length=500,
                upload_to="power_sources/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "webp"]
                    ),
                    products.models.validate_product_image_file_size,
                ],
            ),
        ),
    ]
