# Generated by Django 6.0.2 on 2026-02-14 10:54

import django.core.validators
import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_powersource_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productcatalogue",
            name="file_url",
        ),
        migrations.CreateModel(
            name="ProductCatalogueFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=500,
                        upload_to="product_catalogues/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            ),
                            products.models.validate_product_document_file_size,
                        ],
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "catalogue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="products.productcatalogue",
                    ),
                ),
            ],
            options={
                "db_table": "product_document_files",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
