# Generated by Django 6.0.2 on 2026-02-14 10:59

import django.core.validators
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_remove_productcatalogue_file_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcatalogue",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="product_catalogues/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    ),
                    products.models.validate_product_document_file_size,
                ],
            ),
        ),
        migrations.DeleteModel(
            name="ProductCatalogueFile",
        ),
    ]
