# Generated by Django 6.0.2 on 2026-02-16 06:57

import django.core.validators
import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_productcatalogue_file_delete_productcataloguefile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="accessories_mounting",
        ),
        migrations.RemoveField(
            model_name="product",
            name="actuation_type",
        ),
        migrations.RemoveField(
            model_name="product",
            name="applications",
        ),
        migrations.RemoveField(
            model_name="product",
            name="certifications",
        ),
        migrations.RemoveField(
            model_name="product",
            name="control_type",
        ),
        migrations.RemoveField(
            model_name="product",
            name="double_acting_torque",
        ),
        migrations.RemoveField(
            model_name="product",
            name="enclosure_rating",
        ),
        migrations.RemoveField(
            model_name="product",
            name="features",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.RemoveField(
            model_name="product",
            name="mounting_standard",
        ),
        migrations.RemoveField(
            model_name="product",
            name="operating_pressure_max",
        ),
        migrations.RemoveField(
            model_name="product",
            name="output_torque_max",
        ),
        migrations.RemoveField(
            model_name="product",
            name="output_torque_min",
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_type",
        ),
        migrations.RemoveField(
            model_name="product",
            name="spring_return_torque",
        ),
        migrations.RemoveField(
            model_name="product",
            name="temperature_high_max",
        ),
        migrations.RemoveField(
            model_name="product",
            name="temperature_low_min",
        ),
        migrations.RemoveField(
            model_name="product",
            name="temperature_standard_max",
        ),
        migrations.RemoveField(
            model_name="product",
            name="temperature_standard_min",
        ),
        migrations.RemoveField(
            model_name="product",
            name="testing_standard",
        ),
        migrations.RemoveField(
            model_name="product",
            name="thrust_max",
        ),
        migrations.RemoveField(
            model_name="product",
            name="thrust_min",
        ),
        migrations.RemoveField(
            model_name="product",
            name="valve_compatibility",
        ),
        migrations.AddField(
            model_name="product",
            name="specification",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        max_length=500,
                        upload_to="products/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "webp"]
                            ),
                            products.models.validate_product_image_file_size,
                        ],
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_images",
                "ordering": ("display_order", "id"),
            },
        ),
    ]
