# Generated by Django 6.0.2 on 2026-02-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_remove_product_accessories_mounting_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AddField(
            model_name="product",
            name="features",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="ProductCategory",
        ),
    ]
