# Generated by Django 6.0.2 on 2026-02-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_remove_product_category_product_features_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="torque_max_nm",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="torque_min_nm",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
    ]
