# Generated by Django 6.0.2 on 2026-02-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_product_torque_max_nm_product_torque_min_nm"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="thrust_max_n",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="thrust_min_n",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
    ]
