# Generated by Django 6.0.2 on 2026-02-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_product_thrust_max_n_product_thrust_min_n"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["is_visible", "power_source"], name="prod_vis_pow_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["created_at"], name="prod_created_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["is_visible", "-created_at"], name="prod_vis_created_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["torque_min_nm"], name="prod_torque_min_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["torque_max_nm"], name="prod_torque_max_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["thrust_min_n"], name="prod_thrust_min_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["thrust_max_n"], name="prod_thrust_max_idx"),
        ),
    ]
