# Generated by Django 6.0.2 on 2026-02-20

import django.core.validators
from django.db import migrations, models

import products.models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_add_product_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="industry",
            name="accent_color",
            field=models.CharField(
                default="#FFFFFF",
                max_length=32,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Accent color must be a hex color (e.g. #FF2301) or named color (e.g. white).",
                        regex="^(#[0-9A-Fa-f]{6}|#[0-9A-Fa-f]{3}|[A-Za-z]+)$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="industry",
            name="image_url",
            field=models.ImageField(
                blank=True,
                max_length=500,
                upload_to="industries/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "webp", "jpg", "jpeg"]
                    ),
                    products.models.validate_product_image_file_size,
                ],
            ),
        ),
    ]
