# Generated by Django 6.0.2 on 2026-02-24 05:31

import django.core.validators
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_add_product_indexes"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="industry",
                    name="accent_color",
                    field=models.CharField(
                        default="#FFFFFF",
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                                "Accent color must be a valid hex color (e.g. #FFF or #FFFFFF).",
                            )
                        ],
                    ),
                ),
                migrations.AddField(
                    model_name="industry",
                    name="image_url",
                    field=models.ImageField(
                        blank=True,
                        max_length=500,
                        upload_to="industries/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "webp"]
                            ),
                            products.models.validate_product_image_file_size,
                        ],
                    ),
                ),
            ],
        ),
    ]
