# Generated by Django 6.0.2 on 2026-02-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_industry_image_and_accent_color"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="industry",
            index=models.Index(fields=["is_visible", "sort_order", "name"], name="ind_vis_sort_name_idx"),
        ),
    ]
