# Generated by Django 6.0.2 on 2026-02-06 11:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogueEmailRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        validators=[
                            django.core.validators.RegexValidator(
                                ".*\\S.*", "Company name cannot be blank."
                            )
                        ],
                    ),
                ),
                ("request_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("request_location", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "catalogue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_requests",
                        to="products.productcatalogue",
                    ),
                ),
            ],
            options={
                "db_table": "catalogue_email_requests",
            },
        ),
    ]
