# Generated by Django 6.0.2 on 2026-02-18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InquiryRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("inquiry_reason", models.CharField(max_length=120)),
                ("preferred_language", models.CharField(blank=True, max_length=80)),
                ("company_name", models.CharField(blank=True, max_length=200)),
                (
                    "request_details",
                    models.TextField(
                        blank=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                10, "Please add at least 10 characters."
                            )
                        ],
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=100)),
                ("business_address", models.CharField(blank=True, max_length=255)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9+\\-\\s()]*$", "Invalid phone number format."
                            )
                        ],
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("subscribe_updates", models.BooleanField(default=False)),
                ("request_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "inquiry_requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
