# Generated by Django 6.0.2 on 2026-02-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_inquiryrequest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="catalogueemailrequest",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="catalogueemailrequest",
            name="attempt_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="catalogueemailrequest",
            name="failure_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="catalogueemailrequest",
            name="last_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="catalogueemailrequest",
            name="product_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="catalogueemailrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("SENT", "Sent"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
    ]
